root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o bin/healthchecker.exe ./cmd/server"
bin = "bin/healthchecker.exe"
include_ext = ["go"]
exclude_dir = ["vendor", "bin", "tmp"]

[log]
time = true

[dev]
cmd = "./bin/healthchecker.exe"
